sudo: false
before_script:
- gem install sass
- npm install -g gulp
- npm install
script:
- gulp bower
- gulp
deploy:
  provider: s3
  access_key_id: AKIAJ6X4LPAAM3MPNULQ
  secret_access_key:
    secure: SOUNeqm2oAgr9btpSdAYgRtOa4zp8HaVGoph8wh0NqickRCdDOL557AaQ9Xe48emEI29eN5UtOjR3Gw+FGR5mFIIuBsrnM7gHG5W452dWurF6uoxSujiI0EJpY+sQeIuyUzQMWHs5LoxVNZ/dng4pLDyeNg+gLuK3P/NR7gBRI9k9g7PowPXhr46pdOh2bUowkwt5qkKVC2RWvO9sCM6BfmWJO+JvFH6Pqwx+TqU6mc+Wo+PGWSyFAsBte5QT+LcK+RP3BXPHydJcKa3R4xhKBm/x2Q5vxvk8OQmLMhF+kTPr/XtSeVstxpQxY85RQAGQ0fE2YZV28kzyT7Wn7MXNUQ66rlBKZUwMWi3gvQpfTGZ+UiR1DPYArHdEEE1iiYcFVKI64MdPLWFLTLzuj2Z1j2ZN0ttHRCZ/mf3GIN7m3/YzFGyAvVUhq9HRi9081y+m5XtzhwpIDkEXAQmCJKEAHi+E3eXYK2oHbQbMq9S7D3SBm809S5phag4NNUZc8EtNGdzTVH3TKf0yVD/I1VnzSGMhpETWdEk1s05DW1P1Wo0j1KJGCUsJAHrdb8/aOJKa7gvGOGxmx4R/y4lzFd9t0/ckIGnSqJmOKUq14ZbDCbrz+pCBLDYKricAqt9sbTDylxB/VmMoDhyIdHsCiXDkjvAbTcsmruwvT/PyvAtq98=
  bucket: whitetreehr.co.uk
  region: eu-west-2
  skip_cleanup: true
  local-dir: web
  acl: public_read
  on:
    repo: bobbydeveaux/whitetreehr.co.uk
