sudo: false
before_script:
- gem install sass
- npm install -g gulp
- npm install
script:
- gulp bower
- gulp
deploy:
  provider: s3
  access_key_id: AKIAIGKXVNFPSU7YOGYQ
  secret_access_key:
    secure: vm/VGebBkLd8BR1uyZJ/p6KUpjlq37s7wDlv0I+NcqQYuM0/Lf1nDxkVssv5oGPRyXPsWZIzqJH9fHqxhFfHcZ96uuyA9e7HP2iXs0Dx0JcISARom2g5YFBHIJdTCja9gpSLHbowRfYfEmconhAyox421wmK+Owt0j7p9VnmrvaVIamcsQSC1QNj8ACExZQDx9lOig3HPfhhqSlRKsJJz+cZAuqcvOgT36V3xGrg8tPMtHr7Cj1ipyqzzjfGkfYTkailjQJcZGHtTGVfKdKadRc4+S4As+C7+hTYoafc1V40Yfw/q/0SnYC9qPcgPh8TJOOXN8dkJr+0DlbsNa6rbjX1sK9uP3xgY6XNqaGkirEse02l1GOYZliqHR1WT/QmIvZY+kMFqQ72xkRQACXfloU2xPjX7kW0DsmDbw2UFxsOW/yISHWY35P0G6vNYA00jmu4QGZqMT64nqk1NMefKWb/UJ5V91LurOtZIjkP9Gu4zpY8GFMcbM33e2v+xUtlI99YdEwl7u4jJ//nZftz3beGAQSH6PU/q7BlTVOE9W+uItYi7wdn9Jv8hKNCp2nzQT7WOQ5vCAwHR6SaaBsxery2NXy5cDLLJFKF9CelbnZqCZd+H7uvIKrS8u1R6e3sLtAbAaMooF1QuWB/lGSYL7lEOdRCOavsSqQI1th2swI=
  bucket: whitetreehr.co.uk
  region: eu-west-2
  skip_cleanup: true
  local-dir: web
  acl: public_read
  on:
    repo: bobbydeveaux/whitetreehr.co.uk
